services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  frontend:
    image: antipinsite/artist-frontend:latest
    restart: always

  backend:
    image: antipinsite/artist-backend:latest
    volumes:
      - ./backend/src:/app/src
      - ./backend/config:/app/config
      - ./backend/public:/app/public
      - ./backend/database:/app/database
    environment:
      - NODE_ENV=development
      - DATABASE_FILENAME=database/data.db
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=key1,key2,key3
      - API_TOKEN_SALT=salt
      - ADMIN_JWT_SECRET=secret
      - JWT_SECRET=secret
      - PUBLIC_URL=https://localhost

volumes:
  caddy_data:
  caddy_config: